import { getAutoGeneratedPlaylist, getFllowersProfile, getFollowersProfilePublic, getFollowingsProfile, getPublicPlaylist, getPublicProfile, getPublicUploads, getRecommendByProfile, getUploads, updatedFollower } from "#/controllers/follower";
import { getPlaylistAudios, getPrivatePlaylistAudios } from "#/controllers/playlist";
import { isAuth, mustAuth } from "#/middleware/auth";
import { Router } from "express";


const router = Router();
router.post("/update-follower/:profileId", mustAuth, updatedFollower);
router.get('/uploads', mustAuth, getUploads);
router.get("/uploads/:profileId", getPublicUploads);
router.get("/info/:profileId", getPublicProfile);
router.get("/playlist/:profileId", getPublicPlaylist);
router.get("/recommended", isAuth,getRecommendByProfile);
router.get("/auto-generated-playlist", mustAuth,getAutoGeneratedPlaylist);
router.get("/followers", mustAuth, getFllowersProfile);
router.get("/followers/:profileId", mustAuth, getFollowersProfilePublic);
router.get("/followings", mustAuth,getFollowingsProfile);
router.get("/playlist-audios/:playlistId", getPlaylistAudios)
router.get("/private-playlist-audios/:playlistId", mustAuth, getPrivatePlaylistAudios);

export default router;