import { RequestWithFiles } from "#/middleware/fileParser";
import { CategoriesType } from "#/models/audio_category";
import { RequestHandler } from "express";
import formidable from "formidable";
import cloudinary from "#/cloud";
import Audio, { AudioDocument } from "#/models/audio";
import { Types, HydratedDocument } from "mongoose";
import { PopulateFavList } from "#/@types/audio";
import AutoGeneratedPlaylist from "#/models/autoGeneratedPlaylist";

interface CreateAudioRequest extends RequestWithFiles {
    body: {
        title: string;
        about: string;
        category: CategoriesType;
    }
}

export const createAudio: RequestHandler = async (req: CreateAudioRequest, res) => {
    const { title, about, category } = req.body;
    const poster = req.files?.poster as formidable.File;
    const audioFile = req.files?.file as formidable.File;
    const ownerId = req.user.id;

    if (!audioFile) return res.status(422).json({ error: "Audio file is missing!" });

    const audioResult = await cloudinary.uploader.upload(audioFile.filepath, {
        resource_type: "video"
    });
    const newAudio = new Audio({
        title,
        about,
        category,
        owner: ownerId,
        file: {
            url: audioResult.url,
            publicId: audioResult.public_id,
        }
    });
    if (poster) {
        const posterResult = await cloudinary.uploader.upload(poster.filepath, {
            width: 500,
            height: 500,
            crop: "thumb",
            gravity: "face"
        });
        newAudio.poster = { url: posterResult.secure_url, publicId: posterResult.public_id };
    }
    await newAudio.save();
    res.status(201).json({
        audio: {
            title, about, file: newAudio.file.url,
            poster: newAudio.poster?.url
        }
    });
}

export const updateAudio: RequestHandler = async (req: CreateAudioRequest, res) => {
    const { title, about, category } = req.body;
    const poster = req.files?.poster as formidable.File;
    const audioFile = req.files?.file as formidable.File;
    const ownerId = new Types.ObjectId(req.user.id);
    const audioId = new Types.ObjectId(req.params.audioId as string);

    const audio = await Audio.findOneAndUpdate(
        { owner: ownerId, _id: audioId },
        { title, about, category },
        { new: true }
    ) as HydratedDocument<AudioDocument> | null;

    if (!audio) return res.status(404).json({ error: 'Âm thanh không tồn tại hoặc không có quyền truy cập!' });

    if (audioFile) {
        if (audio.file?.publicId) {
            await cloudinary.uploader.destroy(audio.file.publicId, { resource_type: "video" });
        }
        const audioResult = await cloudinary.uploader.upload(audioFile.filepath, {
            resource_type: "video"
        });
        audio.file = {
            url: audioResult.secure_url,
            publicId: audioResult.public_id
        };
        await audio.save();
    }

    if (poster) {
        if (audio.poster?.publicId) {
            await cloudinary.uploader.destroy(audio.poster.publicId);
        }
        const posterResult = await cloudinary.uploader.upload(poster.filepath, {
            width: 500,
            height: 500,
            crop: "thumb",
            gravity: "face"
        });
        audio.poster = {
            url: posterResult.secure_url,
            publicId: posterResult.public_id
        };
        await audio.save();
    }

    res.status(200).json({
        audio: {
            title: audio.title,
            about: audio.about,
            category: audio.category,
            file: audio.file.url,
            poster: audio.poster?.url
        }
    });
};

export const getAudio: RequestHandler = async (_req, res) => {
    const audio = await Audio.find({}).sort({ createdAt: -1 });
    res.status(200).json({ audio });
}

export const deleteAudio: RequestHandler = async (req, res) => {
    const ownerId = new Types.ObjectId(req.user.id);
    const audioId = new Types.ObjectId(req.params.audioId as string);

    const audio = await Audio.findOneAndDelete({ owner: ownerId, _id: audioId }) as HydratedDocument<AudioDocument> | null;
    if (!audio) return res.status(404).json({ error: "Âm thanh không tồn tại hoặc không có quyền truy cập!" });
    if (audio.file.publicId) {
        await cloudinary.uploader.destroy(audio.file.publicId, { resource_type: "video" });
    }
    if (audio.poster?.publicId) {
        await cloudinary.uploader.destroy(audio.poster.publicId);
    }
    res.status(200).json({ message: "Âm thanh đã được xóa thành công!", audioId });
}

export const getLatestUploads: RequestHandler = async (req, res) => {
    const list = await Audio.find().sort("-createdAt")
        .limit(10).populate<PopulateFavList>("owner");
    const audios = list.map((item) => {
        return {
            id: item._id,
            title: item.title,
            about: item.about,
            category: item.category,
            file: item.file.url,
            poster: item.poster?.url,
            owner: {
                name: item.owner.name,
                id: item.owner._id
            }
        }
    });
    res.json({ audios })
}
