import { Schema, Types } from "mongoose";
import { model, models, Model } from "mongoose";

interface AutoPlaylistDocument {
    title: string;
    items: (Types.ObjectId | string)[];
}

const autoplaylistSchema = new Schema<AutoPlaylistDocument>({
    title: {
        type: String,
        required: true
    },
    items: [{
        type: Schema.Types.ObjectId,
        required: true,
        ref: "Audio"
    }],
}, { timestamps: true });

const AutoGeneratedPlaylist = models.AutoGeneratedPlaylist || model("AutoGeneratedPlaylist", autoplaylistSchema);
export default AutoGeneratedPlaylist as Model<AutoPlaylistDocument>;
